In [1]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6) # one dimensional array
x2 = np.random.randint(10, size=(5, 4)) # two dimensional array
x3 = np.random.randint(10, size=(5,6,9)) # three dimensional array

In [3]:
print("*************** 1) One dimensional array ****************")
print(x1)

print("*************** 2) Two dimensional array ****************")
print(x2)

print("*************** 3) Three dimensional array ****************")
print(x3)

*************** 1) One dimensional array ****************
[5 0 3 3 7 9]
*************** 2) Two dimensional array ****************
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]
 [8 1 5 9]
 [8 9 4 3]]
*************** 3) Three dimensional array ****************
[[[0 3 5 0 2 3 8 1 3]
  [3 3 7 0 1 9 9 0 4]
  [7 3 2 7 2 0 0 4 5]
  [5 6 8 4 1 4 9 8 1]
  [1 7 9 9 3 6 7 2 0]
  [3 5 9 4 4 6 4 4 3]]

 [[4 4 8 4 3 7 5 5 0]
  [1 5 9 3 0 5 0 1 2]
  [4 2 0 3 2 0 7 5 9]
  [0 2 7 2 9 2 3 3 2]
  [3 4 1 2 9 1 4 6 8]
  [2 3 0 0 6 0 6 3 3]]

 [[8 8 8 2 3 2 0 8 8]
  [3 8 2 8 4 3 0 4 3]
  [6 9 8 0 8 5 9 0 9]
  [6 5 3 1 8 0 4 9 6]
  [5 7 8 8 9 2 8 6 6]
  [9 1 6 8 8 3 2 3 6]]

 [[3 6 5 7 0 8 4 6 5]
  [8 2 3 9 7 5 3 4 5]
  [3 3 7 9 9 9 7 3 2]
  [3 9 7 7 5 1 2 2 8]
  [1 5 8 4 0 2 5 5 0]
  [8 1 1 0 3 8 8 4 4]]

 [[0 9 3 7 3 2 1 1 2]
  [1 4 2 5 5 5 2 5 7]
  [7 6 1 6 7 2 3 1 9]
  [5 9 9 2 0 9 1 9 0]
  [6 0 4 8 4 3 3 8 8]
  [7 0 3 8 7 7 1 8 4]]]
